network:
  version: 2
  ethernets:
    k8s0:
      dhcp4: no
      dhcp6: no
      mtu: 1450
      addresses:
        - IFADDR/32
      routes:
        - to: IFROUTE/32
          scope: link
        - to: IFNETWORK
          via: IFROUTE
      match:
        name: en*s0
      set-name: k8s0
