network:
  version: 2
  ethernets:
    ens00:
      dhcp4: no
      dhcp6: no
      mtu: 1450
      addresses: [192.168.1.1/32]
      routes:
        - to: 192.168.0.1/32
          scope: link
        - to: 192.168.0.0/16
          via: 192.168.0.1
