network:
  version: 2
  ethernets:
    IFNAME:
      dhcp4: no
      dhcp6: no
      mtu: 1450
      addresses:
        - IFADDR/32
      routes:
        - to: IFROUTE/32
          from: IFADDR
          scope: link
        - to: IFNETWORK
          via: IFROUTE
          from: IFADDR
