network:
  version: 2
  ethernets:
    IFNAME:
      dhcp4: no
      dhcp6: no
      mtu: 1450
      addresses:
        - IFADDR
      routes:
        - to: IFROUTE/32
          scope: link
        - to: IFNETWORK
          via: IFROUTE
